### ISSUE TITLE
JSON LD and Structured Data

### ISSUE THREAD

**Issue by danpastori** [themsaid/wink#118]
First off, thanks for making Wink! 

Is there anything on the roadmap for supporting JSON-LD for structured data? Currently, we can use some settings to generate this in a template, but there are a few fields that would be nice to add to posts and settings to make this process easier. Here is a link for more information on the other fields that can be used for JSON-LD: https://developers.google.com/search/docs/guides/intro-structured-data.

If you are interested in this, I can help develop the functionality and submit a PR. Thanks again for making Wink!

**Comment by themsaid** [comment]
That's interesting indeed. You could open a PR where you add the extra fields to the "SEO & Social" modal.
