### ISSUE TITLE
Guidelines / hooks for creating Wink addons / plugins

### ISSUE THREAD

**Issue by connecteev** [themsaid/wink#120]
I know now that we want to keep Wink lightweight and avoid the bloat. At the same time I see here that you're open to wink addons or plugins to extend the functionality:
https://github.com/writingink/wink/issues/115

I can think of several possible addons:
1. Specify "Post Types" (like articles, podcast episodes, Quick Tips, etc) : This would involve adding a "type" field to the wink_posts table.
2. Category hierarchy (Separate from tags)
3. Front-end themes (with related posts, latest posts, etc)
4. Commenting system
etc etc etc

If there a set of guidelines / hooks for creating wink addons / plugins?

**Comment by themsaid** [comment]
Haven't thought about that yet TBH :) Will try to work on that in the next few weeks.

**Comment by connecteev** [comment]
Awesome, can't wait. 
Once we have the guidelines and hooks for creating extensions defined, the # of community contributions to Wink will start to take off. I can think of tons of ideas for packages to make wink more powerful as a CMS (like the ones above), and doing it this way will let you keep the core lean.

**Comment by morpheus7CS** [comment]
I think this is a great approach. It would allow “Wink package creators” to submit their own functionality from the roadmap and ideas section and if those prove useful to the wider community, they could be merged into the core. We’re already using Wink in production for 2 client projects and would like to extend the functionality in terms of Categories, Localization and Multi-Lingual setup.

**Comment by connecteev** [comment]
Any thoughts on this, @themsaid ? I really want to add categories to mywink blog posts would be great to either add those or define how we can extend wink with plugins, while still being able to pull from the master codebase.

**Comment by ana-lisboa** [comment]
"Multi-Lingual setup" would be the cherry on top of a cake!
