### ISSUE TITLE
S3 Filesystem Not Working

### ISSUE THREAD

**Issue by intellow** [themsaid/wink#156]
I have an s3 bucket successfully configured for my app. It is working for all the non-wink parts of my application.

I've added the following items to my .env:

```
WINK_STORAGE_DISK=s3
WINK_STORAGE_PATH=wink
```

However, when I try to upload an image I get the following error:

`Error executing "PutObject" on "https://my-bucket.s3.us-west-1.amazonaws.com/wink/mJBwl4ixQzI9qcsLEttzghNapLxaFrquST74I6MQ.jpeg"; AWS HTTP error: Client error: `PUT https://my-bucket.s3.us-west-1.amazonaws.com/wink/mJBwl4ixQzI9qcsLEttzghNapLxaFrquST74I6MQ.jpeg` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7A693D (truncated...) AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7A693D29C79D3BDF</RequestId><HostId>JQEG2o5QcFxqq8oIVQkaGfDJcbBRKojgCmSNFXl0A6k2PlSLadOqVdXNyT4uxmxihXNYxHv9S/E=</HostId></Error>`

**Comment by themsaid** [comment]
hmm we use it on blog.laravel.com and it seems to be working fine for us. Are you sure you are on the latest Wink?

**Comment by intellow** [comment]
> hmm we use it on blog.laravel.com and it seems to be working fine for us. Are you sure you are on the latest Wink?

Yep, I just installed it 2 days ago, so I must be on the latest. My S3 policy allows the authenticated user I created in IAM to have access to all S3 actions. Again, those credentials are working in the non-wink aspects of the app. In case this is helpful, here is my S3 bucket policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<my-user>"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::padmission-dev-public/*",
                "arn:aws:s3:::padmission-dev-public"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::padmission-dev-public/*"
        }
    ]
}
```

**Comment by opmvpc** [comment]
@intellow I had the same issue and had to uncheck those in my bucket config :
![image](https://user-images.githubusercontent.com/14226423/56091289-76fa9e80-5ead-11e9-8f62-479422d63bba.png)
But I don't know if it is a good practice. 😨 

Hope it helps!

**Comment by nlehman06** [comment]
I'm having the same issue as @intellow. 
@opmvpc  Your solution worked for me but I'm curios if this is the best/safest way to handle this.

**Comment by divyamanchireddy19** [comment]
did anyone solve this without changing the public option?

**Comment by nolannordlund** [comment]
I'm running into this also but I am not able to fix it by making the bucket public.

**Comment by nolannordlund** [comment]
I ended up unchecking every option in the "Block public access" section and I also added the following policy so that Wink could read and write to the bucket:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Public",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME/*"
        }
    ]
}
```

**Comment by dircm** [comment]
It seems S3 has had some updates, to get Wink to be able to upload images I needed to change the owner-enforced property to owner-preferred and "restore ACLs" 
![image](https://user-images.githubusercontent.com/18188561/179125791-208f3ac3-6142-48a9-8c78-6e86d6ca26c2.png)

my policy remains :

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::preview.aeroquote.com/*"
        }
    ]
}
```

**Comment by aifodu** [comment]
In my case, even after modifying bucket permissions, I kept getting the error:

`
Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0
` 

Slightly modifying the upload function in ImageUploadsController seemed to fix the issue. Here's the modification:

```
public function upload()
{
    $path = Storage::disk(config('wink.storage_disk'))->put(config('wink.storage_path'), request()->image);

    return response()->json([
        'url' => Storage::disk(config('wink.storage_disk'))->url($path),
    ]);
}
```
