### ISSUE TITLE
Feature request: Page Categories

### ISSUE THREAD

**Issue by rkmaier** [themsaid/wink#195]
I saw the request for having post categories, while I agree It doesn't really make sense for posts if tags are being used, for the pages section I think it would be useful to have the ability to group some of the static pages that are being created by having categories for them. What do you think ?

**Comment by BrayanAngaritaR** [comment]
Tags are fine, but adding categories would be super important for the blog.

**Comment by themsaid** [comment]
I'd happily accept a PR :)

**Comment by edionmelarosa** [comment]
I am working on this feature
