### ISSUE TITLE
wink:migrate command is not working

### ISSUE THREAD

**Issue by ArielMejiaDev** [themsaid/wink#250]
Hi, first I really love your package, thanks for your work, I try five times to install wink with a fresh Laravel installations, I follow the readme.md, all the times it returns me the same error:

```
Base table or view not found: 1146 Table 'project.wink_authors' doesn't exist
```

My wink db connection is on ".env" file:

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=project
DB_USERNAME=root
DB_PASSWORD=
WINK_DB_CONNECTION=mysql
```

I work previously with this package, so I try adding in "config/database.php" another db connection as wink, by coping the "mysql" driver and rename it as "wink", but this does not work either.

I suppose that the command:

```
php artisan wink:install
```

publish assets, but not a migrations, maybe there is a key, thanks for all your work for the community.

**Comment by devcircus** [comment]
php artisan wink:migrate runs the migrations to create the missing tables

**Comment by themsaid** [comment]
Run `wink:migrate` after `wink:install` as in the readme file.

**Comment by ArielMejiaDev** [comment]
Thanks, I really try again with a fresh installation,  I am using the laravel installer.

I run composer require command, then ```wink:install``` it works, then I run the ```wink:migrate``` and it throws the same error.

I already used this package, (https://arielmejiadevblog.xyz/admin/posts), but I dont know why this time it fail.

I follow the readme and I try again, just in case I follow the same steps as the Laravel daily video: https://www.youtube.com/watch?v=4HongftE3wM&t=159s just change the package name, because the vendor change.

Thanks for the quickly response, I appreciate the effort and the time, thanks!

**Comment by DominikGeimer** [comment]
I still geht that error on a fresh laravel installation.

**Comment by vimalmistry** [comment]
Exact same issue. Any update on this? I followed all steps from documents.

**Comment by devcircus** [comment]
Have you configured the wink db connection and created the corresponding table?

**Comment by vimalmistry** [comment]
> Have you configured the wink db connection and created the corresponding table?

I configured connection in wink and executed wink:install command. But wink:migrate not working.

**Comment by vimalmistry** [comment]
![Screenshot 2020-06-08 at 5 25 09 PM](https://user-images.githubusercontent.com/3993163/84027828-3f9e5980-a9ad-11ea-87d3-6ef33afdf7cc.png)

**Comment by ChrisRouxel** [comment]
Hi, is there any update to this, I am encountering the same issue, I have run all the steps as instucted in the readme, but I'm also encountering the same issue.

````
Migration table created successfully.
Nothing to migrate.

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'locavra_cms.wink_authors' doesn't exist (SQL: insert into `wink_authors` (`id`, `name`, `slug`, `bio`, `email`, `password`, `updated_at`, `created_at`) values (8e752b02-50ca-41a4-8cd5-4c41cbcd5459, Regina Phalange, regina-phalange, This is me., admin@mail.com, $2y$10$E/5b1x7qDXKvsoM.jLfhGeBagxjYbWIdrL/.3X.n2h8RygjIfLk96, 2020-06-19 07:33:56, 2020-06-19 07:33:56))

  at /Users/chrisrouxel/Sites/locavra/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|
````

I've tried clearing the migration take - my wink connection works becuase it can create the migration table - I'm scratching my head here as to what's missing.

**Comment by fgoni** [comment]
If everyone else is having this issue, this happens on **7.2** environments, where **0.2** version is pulled instead of **1.0.***

In `MigrateCommand` it will try to do this:

```php
        $this->call('migrate', [
            '--database' => config('wink.database_connection'),
            '--path' => 'vendor/writingink/wink/src/Migrations',
        ]);
```

When it should be doing this:

```php
        $this->call('migrate', [
            '--database' => config('wink.database_connection'),
            '--path' => 'vendor/themsaid/wink/src/Migrations',
        ]);
```

Changing that allows the migration file to find the migrations and run them before trying to access the unexisting tables.

**Comment by mochoge** [comment]
> If everyone else is having this issue, this happens on **7.2** environments, where **0.2** version is pulled instead of **1.0.***
> 
> In `MigrateCommand` it will try to do this:
> 
> ```
>         $this->call('migrate', [
>             '--database' => config('wink.database_connection'),
>             '--path' => 'vendor/writingink/wink/src/Migrations',
>         ]);
> ```
> 
> When it should be doing this:
> 
> ```
>         $this->call('migrate', [
>             '--database' => config('wink.database_connection'),
>             '--path' => 'vendor/themsaid/wink/src/Migrations',
>         ]);
> ```
> 
> Changing that allows the migration file to find the migrations and run them before trying to access the unexisting tables.

@fgoni This solves the issue. Thanks.
