### ISSUE TITLE
Code highlighter acting weird - not styling tags correctly

### ISSUE THREAD

**Issue by oliverbj** [themsaid/wink#257]
Hi there!

I am currently writing a new blog post, running Wink version 1.0.3. In this blog post, I need to write below code:

```html
<body class="bg-white">
</body>
```

When I wrap that in the code tag, this is the output:

[![enter image description here][1]][1]

The thing here is, that the closing `</body`> tag, is not being formatted correctly. Looking at the page source, this is the generated HTML:

```
<pre class="ql-syntax" spellcheck="false">&lt;body 
   <span class="hljs-class">
       <span class="hljs-keyword">class</span>
   </span>
    =
    <span class="hljs-string">"bg-white dark:bg-black"</span>
    &gt;
    <span class="hljs-tag">&lt;/
        <span class="hljs-name">body</span>
        &gt;
    </span>
</pre>
```

As you can see, the closing body is wrapped in a `hljs-name` tag, while the opening tag is only treated as a string.

  [1]: https://i.stack.imgur.com/pEaaI.png

**Comment by themsaid** [comment]
If you add a Doctype tag, it'll style the code correctly:

```
<!DOCTYPE html>
<body class="white">
</body>
```

The is with https://github.com/highlightjs/highlight.js/ not Wink.
