### ISSUE TITLE
Error with the vendor path on the migration command from installation

### ISSUE THREAD

**Issue by vitorarjol** [themsaid/wink#271]
Hi @themsaid! First of all thank you for this great package!

I was setting up my blog app and every time I was executing the `wink:migrate` command it skipped the migrations, went directly to the seeder and than failed.

I also tried to run directly the `artisan migrate --path vendor/**writingink**/wink/src/Migrations`, and the result was "nothing to migrate".

After some debugging, I saw that the path used is referencing to **writingink**, but in my vendor fold this package it's in the **themsaid** folder. After changing this path everything worked out just fine. Is this setting correct? I can send a PR to update this if it's really a bug, 

😄

**Comment by themsaid** [comment]
What version of Wink are you running?

**Comment by vitorarjol** [comment]
Just checked, and for some reason I'm on version 0.2.0.

Did a fresh install of laravel 7 and after that followed the readme `composer require themsaid/wink`.

Certainly that's the issue. I'll look further to see if I can find any issues with composer or cache. Closing this for now.

Thank you!
