### ISSUE TITLE
Session table issue with Laravel 8 + Jetstream

### ISSUE THREAD

**Issue by mukarramkhalid** [themsaid/wink#290]
Hi,

I installed Laravel 8 with Jetstream which uses default database session driver out of the box.

It creates a `sessions` table having `user_id` column with type BigInt.

As soon as I login to mydomain.com/wink, I get the following error.

```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update `sessions` set `payload` = YTo0OntzOjY6Il90b2tlbiI7c..., `user_id` = 3f5c4ff0-3923-4ebb-ad4d-3cca3fabb9fb, `ip_address` = 127.0.0.1, `user_agent` = Mozilla/5.0 where `id` = ksqEGwiSy4qq8vmbhc9rnXTBL9cMZYPs4VJpCjYj)
```

Which makes sense because `user_id` column in sessions table doesn't support `id` from authors table. 

Is this package not supported with Jetstream/Fortify yet, or am I missing something?

Thanks.

**Comment by DominikGeimer** [comment]
Workaround: In your .env file change the session driver to `SESSION_DRIVER=file`

**Comment by bgencacat** [comment]
Workaround: Change user_id column type as varchar

**Comment by skino2019** [comment]
> Hi,
> 
> I installed Laravel 8 with Jetstream which uses default database session driver out of the box.
> 
> It creates a `sessions` table having `user_id` column with type BigInt.
> 
> As soon as I login to mydomain.com/wink, I get the following error.
> 
> ```
> SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update `sessions` set `payload` = YTo0OntzOjY6Il90b2tlbiI7c..., `user_id` = 3f5c4ff0-3923-4ebb-ad4d-3cca3fabb9fb, `ip_address` = 127.0.0.1, `user_agent` = Mozilla/5.0 where `id` = ksqEGwiSy4qq8vmbhc9rnXTBL9cMZYPs4VJpCjYj)
> ```
> 
> Which makes sense because `user_id` column in sessions table doesn't support `id` from authors table.
> 
> Is this package not supported with Jetstream/Fortify yet, or am I missing something?
> 
> Thanks.

Im having the exact same Issue. The work around Dominik Geimer mentioned worked for me. hopefully package is brought inline for Laravel 8.. I love the package

**Comment by Hadi-pd** [comment]
Im having the exact same Issue. I changed user_id column type as varchar

**Comment by Ahmed-max-b** [comment]
in my case, i'm having this error E11000 duplicate key error collection: mongodb.sessions index: id_1 dup key: { id: "zIUMn9kLsakFOdS2fakKqiEgLQhnmctAATfR6NdQ" } when i try to get the register page, i'm using MongoDB as database,
i will so gratefull if someone can help me

**Comment by yevhen113** [comment]
Why is this issue closed? Is project still alive?
