### ISSUE TITLE
Extend default models

### ISSUE THREAD

**Issue by antonkomarev** [themsaid/wink#92]
It will be good to have ability to extend:
- `WinkAuthor`
- `WinkPost`
- `WinkPage`

**Comment by themsaid** [comment]
Can you share an example use case?

**Comment by antonkomarev** [comment]
I've extended default model with my own behavior:
https://github.com/antonkomarev/laravel-love-upgrade/blob/master/app/Models/Post.php

**Comment by rennokki** [comment]
There's a PR linked to that: https://github.com/writingink/wink/pull/140
